# Generated by extendr: do not edit by hand

.read_excel_columns <- function(source, sheet, range, col_names, header_row, skip_rows, n_max, schema_sample_rows, dtype_coercion, dtypes, skip_whitespace_tail_rows, whitespace_as_null) {
  check_extendr_result(.Call(wrap__read_excel_columns, source, sheet, range, col_names, header_row, skip_rows, n_max, schema_sample_rows, dtype_coercion, dtypes, skip_whitespace_tail_rows, whitespace_as_null))
}

.excel_sheets <- function(source) {
  check_extendr_result(.Call(wrap__excel_sheets, source))
}

.excel_tables <- function(source, sheet) {
  check_extendr_result(.Call(wrap__excel_tables, source, sheet))
}

.excel_defined_names <- function(source) {
  check_extendr_result(.Call(wrap__excel_defined_names, source))
}

check_extendr_result <- function(x) {
  if (inherits(x, "extendr_error")) {
    stop(as.character(x$value), call. = FALSE)
  }
  x
}
