# Generated by extendr: do not edit by hand

.read_excel_columns <- function(path, sheet, range, col_names, n_max) {
  check_extendr_result(.Call(wrap__read_excel_columns, path, sheet, range, col_names, n_max))
}

.excel_sheets <- function(path) {
  check_extendr_result(.Call(wrap__excel_sheets, path))
}

.excel_tables <- function(path, sheet) {
  check_extendr_result(.Call(wrap__excel_tables, path, sheet))
}

.excel_defined_names <- function(path) {
  check_extendr_result(.Call(wrap__excel_defined_names, path))
}

check_extendr_result <- function(x) {
  if (inherits(x, "extendr_error")) {
    stop(as.character(x$value), call. = FALSE)
  }
  x
}
