# Generated by extendr: do not edit by hand

.read_excel_columns <- function(source, zip_limits, sheet, range, columns, col_names, header_row, skip_rows, n_max, schema_sample_rows, dtype_coercion, dtypes, skip_whitespace_tail_rows, whitespace_as_null) {
  check_extendr_result(.Call(wrap__read_excel_columns, source, zip_limits, sheet, range, columns, col_names, header_row, skip_rows, n_max, schema_sample_rows, dtype_coercion, dtypes, skip_whitespace_tail_rows, whitespace_as_null))
}

.read_excel_arrow <- function(source, zip_limits, sheet, range, columns, col_names, header_row, skip_rows, n_max, schema_sample_rows, dtype_coercion, dtypes, skip_whitespace_tail_rows, whitespace_as_null, array, schema, single_column) {
  check_extendr_result(.Call(wrap__read_excel_arrow, source, zip_limits, sheet, range, columns, col_names, header_row, skip_rows, n_max, schema_sample_rows, dtype_coercion, dtypes, skip_whitespace_tail_rows, whitespace_as_null, array, schema, single_column))
}

.excel_sheets <- function(source, zip_limits) {
  check_extendr_result(.Call(wrap__excel_sheets, source, zip_limits))
}

.excel_sheet_info <- function(source, zip_limits, sheet) {
  check_extendr_result(.Call(wrap__excel_sheet_info, source, zip_limits, sheet))
}

.excel_tables <- function(source, zip_limits, sheet) {
  check_extendr_result(.Call(wrap__excel_tables, source, zip_limits, sheet))
}

.excel_defined_names <- function(source, zip_limits) {
  check_extendr_result(.Call(wrap__excel_defined_names, source, zip_limits))
}

check_extendr_result <- function(x) {
  if (inherits(x, "extendr_error")) {
    stop(as.character(x$value), call. = FALSE)
  }
  x
}
